// js/index.js
//import './config/jqueryLoad';
//import '@fancyapps/fancybox/dist/jquery.fancybox.min';
//import './jquery.lazymap.js';
//import './jquery.easing.js';
import './bootstrap.js';
import './functions.js';
import './skip-link-focus-fix.js';
import './yall.js';
